### PR TITLE
geojson and data without timestamps as input/start classification at id 0/add trace layer 

### PR DESCRIPTION
**Pull request by sabine-kaiser**

### CODE REVIEW

**Comment by TheMarex** [comment]
Cool! Thanks! Will review this later today. :+1:

**Comment by sabine-kaiser** [comment]
sorry, just saw that somethings are broke :( working on it.

**Comment by sabine-kaiser** [comment]
Ok it works for me, it was just one of my input datasets that was broken -.-

**Comment by TheMarex** [comment]
No worries. Looks good to me. :+1:

**Pull request merged**
